### ISSUE TITLE
Cannot install nlpia on mac osx

### ISSUE THREAD

**Issue by dogrdon** [totalgood/nlpia#16]
I am using the conda installation instructions. My Anaconda python environment is Python 2.7.

When I get up to `pip install -e .`, I get the same error related to Tensorflow:

`Collecting tensorflow (from nlpia==0.1.52.post0.dev11+g939f44e)
  Could not find a version that satisfies the requirement tensorflow (from nlpia==0.1.52.post0.dev11+g939f44e) (from versions: )
No matching distribution found for tensorflow (from nlpia==0.1.52.post0.dev11+g939f44e)`

I have installed tensorflow via `python2.7 -m pip install --user https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.11.0-py2-none-any.whl`

**Comment by Shuyib** [comment]
Try in python 3.x it works well for me besides pandas is not giving so much support for python 2.7

**Comment by dogrdon** [comment]
> Try in python 3.x? it works well for me besides pandas is not giving so much support for python 2.7

So I completely removed my anaconda2 install and installed anaconda3(.6). Setting up the conda environment runs fine. But still getting same error when I run `pip install -e .`

`Collecting tensorflow (from nlpia==0.1.52.post0.dev11+g939f44e)
  Could not find a version that satisfies the requirement tensorflow (from nlpia==0.1.52.post0.dev11+g939f44e) (from versions: )
No matching distribution found for tensorflow (from nlpia==0.1.52.post0.dev11+g939f44e)`

**Comment by dogrdon** [comment]
Final update: shouldn't the instructions at http://nlpia.org/ include entering the new conda environment with `source activate nlpiaenv` before running `pip install -e .`

If I do that, `nlpia` installs.

**Comment by Shuyib** [comment]
> Final update: shouldn't the instructions at http://nlpia.org/ include entering the new conda environment with `source activate nlpiaenv` before running `pip install -e .`?
> 
> If I do that, `nlpia` installs.

I've added it to a new issue. I actually wanted to ask this but i forgot to. Good catch @dogrdon

**Comment by hobson** [comment]
Yes. Thank you for that. Unfortunately one of nlpia's  dependencies (AIML-Bot) require python 3.6. I'll add the line to activate the conda env.
