### ISSUE TITLE
Final update: shouldn't the instructions at http://nlpia.org/ include entering the new conda environment with `source activate nlpiaenv` before running `pip install -e .`?

### ISSUE THREAD

**Issue by Shuyib** [totalgood/nlpia#17]
If I do that, `nlpia` installs.

_Originally posted by @dogrdon in https://github.com/totalgood/nlpia/issues/16#issuecomment-428060170_

**Comment by hobson** [comment]
Yes! You're right.

**Comment by hobson** [comment]
If you add your name to the [AUTHORS](https://github.com/totalgood/nlpia/blob/master/AUTHORS) file and edit the README I'll merge it so you can help others avoid this issue.

**Comment by hobson** [comment]
I went ahead and added some lines like what you suggested and put you in the AUTHORS file
