### ISSUE TITLE
Provide docker version of this

### ISSUE THREAD

**Issue by hoangchunghien** [totalgood/nlpia#19]
Please provide a docker version so we can get started faster

**Comment by hoangchunghien** [comment]
### Create a Dockerfile at the root of the project
`./Dockerfile`
```
FROM jupyter/datascience-notebook

USER root
WORKDIR /home/jovyan/nlpia
COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -e .

WORKDIR /home/jovyan
RUN chown -R jovyan nlpia

EXPOSE 8888

VOLUME [ "~/Documents/GitHub/nlpia/notebooks:/home/jovyan/notebooks" ]
```
### Run following command to build the docker image
`docker build -t nlpia`

### After success build run the image and play arround using `jupyter notebook`
`docker run -p 8888:8888 nlpia`

**Comment by hobson** [comment]
Excellent! Thank you! Have you tested that Dockerfile? If you add your name to the [AUTHORS file](https://github.com/totalgood/nlpia/blob/master/AUTHORS) and put your Dockerfile into a [Pull Request](https://github.com/totalgood/nlpia/pulls) I'll merge it so other's can take advantage of your hard work.
