### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow (from nlpia) (from versions: none)

### ISSUE THREAD

**Issue by nicolamorawetz** [totalgood/nlpia#28]
I'm trying to pip install nlpia but it returns this error and I don't know how to solve it.
Any ideas?

**Comment by hobson** [comment]
We've updated the requirements in setup.cfg so `pip install nlpia` may now work. But if not, you are likely to have better results with Anaconda, following the instructions in the README.md.
