### ISSUE TITLE
OneNeuronRegressor __init__()  returns  self  instead of  None

### ISSUE THREAD

**Issue by TheGhostHuCodes** [totalgood/nlpia#5]
Hi there, I'm following along with chapter 05 of the NLPiA book, and I seem to have hit a snag. I'm trying to make a `OneNeuronRegressor` using the following code:

```Python
from nlpia.models import OneNeuronRegressor

nn = OneNeuronRegressor(alpha=100, n_iter=200)
```

And I get the error:

```IPython
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-5ca2434098df> in <module>()
      1 from nlpia.models import OneNeuronRegressor
      2 
----> 3 nn = OneNeuronRegressor(alpha=100, n_iter=200)

TypeError: __init__() should return None, not 'OneNeuronRegressor'
```

Looking at the latest commit (as of issue submission) it sure looks like `__init__()` for `OneNeuronRegressor` is returning `self` instead of returning `None`.

https://github.com/totalgood/nlpia/blob/67761968083382794f60fb43c86d2e9904287d21/nlpia/models.py#L94

I removed line 94 and it fixes the problem.

**Comment by hobson** [comment]
Fixed using your suggestion. Thank you!
