### ISSUE TITLE
Conda Install Error

### ISSUE THREAD

**Issue by d0tN3t** [totalgood/nlpia#9]
For anyone else running into this conda environment error.

In this step of the env install process: 
`3. # conda install conda/environment.yml`

I was getting an error. I am new to `conda env` so it may just be a beginners mistake. But I came across this stackoverflow solution for my problem: 
https://stackoverflow.com/questions/47214438/errors-when-creating-conda-environment-on-osx

The short answer is your command should look like this:
`conda env create -f conda/environment.yml`

This is the error I was getting:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - conda/environment.yml

Current channels:

  - https://repo.continuum.io/pkgs/main/osx-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by hobson** [comment]
Thank you for the detailed report and fix. README has been corrected.
